[package]
name = "hyperpuzzle_impl_nd_euclid"
description = "N-dimensional Euclidean puzzle backend for Hyperspeedcube"
version = "0.1.0"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
keywords = ["cubing", "hypercubing", "rubik", "4d"]
categories = ["algorithms", "mathematics", "simulation"]
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[dependencies]
hypermath = { workspace = true }
hyperpuzzle_core = { workspace = true }
hyperpuzzlescript = { workspace = true }

disjoint = { workspace = true }
eyre = { workspace = true }
float-ord = { workspace = true }
hypershape = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
regex = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }
tinyset = { workspace = true }
