[package]
name = "hyperpuzzle_view"
description = "View controller for Hyperspeedcube"
version = "0.1.0"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
keywords = ["cubing", "hypercubing", "rubik", "4d"]
categories = ["simulation"]
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[dependencies]
hyperdraw.workspace = true
hypermath.workspace = true
hyperprefs.workspace = true
hyperpuzzle.workspace = true
hyperpuzzle_log.workspace = true

cgmath.workspace = true
eyre.workspace = true
float-ord.workspace = true
itertools.workspace = true
log.workspace = true
parking_lot.workspace = true
smallvec.workspace = true
web-time.workspace = true
