[package]
name = "timecheck"
description = "Scheme for cheating-resistant deterministic games using randomness beacons and time stamp authorities"
version = "0.1.0"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
keywords = ["user-data", "config-directory", "path", "folder", "app_dirs"]
categories = ["filesystem"]
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[dependencies]
chrono = { workspace = true }
drand_core = { workspace = true }
serde = { workspace = true, optional = true }
